### ISSUE TITLE
openwrt网关端编译有没有办法做到不依赖libnetfilter_queue

### ISSUE THREAD

**Issue by kyalipay** [RoyalAliceAcademyOfSciences/DeltaProxyGateway#1]
最近gfw升级了，打算用您这个tcp in udp 来做破墙。
vps服务端编译成功了，但这个网关端一直编译不成功，依赖太多。
openwrt网关端编译有没有办法做到不依赖 libnetfilter_queue（路由器的空间太小，不能装太多缺省编译没有选择的依赖 ），修改代码有没有办法做到不用 queue,  而是让这个程序直接监听本地某个端口 $localport ，再用iptable 转发给它tcp数据，它再去封装成udp，转发给vps服务器一端$remoteip:$remoeport

用这样的方式：

iptables -I zone_lan_forward -p tcp -m multiport --dport 80,443 -m geoip ! --dst-cc CN  -j REDIRECT --to-ports $localport

或类似shadowsocks  ss-redir (tcp in tcp)这样，放在nat表：
iptables -t nat  -p tcp -j REDIRECT --to-ports $localport

**Comment by AuroraRAS** [comment]
感谢您的关注，已经很久没有维护这个项目，里面很多的东西记不太清了。

其实当初开发这个代理主要是为了尝试实现TCP协议中上行和下行的分流，所以对于UDP封装的部分做的比较粗糙，没有做出太多细致思考。依赖libnetfilter_queue也是为了能够直接对数据包进行截获和修改之类的操作，会比较灵活方便，如果进行普通的端口转发从服务器直接返回的数据是会被丢掉的。

很遗憾以我目前掌握的信息还想不出能够减少依赖的更好的方法。

如果您对墙有更多兴趣请加入我们的QQ群共同探讨或参与维护：101891984，加群时请注明您来自Github。

**Comment by kyalipay** [comment]
感谢回复，用 libnetfilter_queue 编译成功了， 用了几天，目前速度很快。
